src/index/urls.py
from django.views.generic import TemplateView
from django.urls import path, include

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name="index"),
    path('user', TemplateView.as_view(template_name='home.html'), name="home")
]

src/roast/urls.py
from django.views.generic import TemplateView
from django.urls import path, reverse_lazy

from roast.views import *

urlpatterns = [
    path('', TemplateView.as_view(template_name='roast.html'), name='roast_test'),
    path('<int:pk>', RoastPage.as_view(), name='roast_page'),
    path('create', RoastList.as_view(), name="create"),
    path('detail/<int:pk>', RoastCrud.as_view(), name="detail"),
]

src/theroast_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.conf import settings

def user_logout(request):
    logout(request)
    return redirect('/')

urlpatterns = [
    path('auth/logout', user_logout, name="logout"),
    path('auth/', include('social_django.urls', namespace='social')),
    path('roast/', include(('roast.urls', 'roast'), namespace='roast')),
    path('admin/', admin.site.urls),
    path('', include(('index.urls', 'index'), namespace="index")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/index/models.py
from django.db import models

# Create your models here.

src/roast/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth import get_user_model

USER_MODEL = get_user_model()

class Roast(models.Model):
    description = models.CharField(max_length=350)

    # Name of the roast
    name = models.CharField(max_length=120)

    # Scale of 1-100 of how dark / light the roast is
    color = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)],
                                default=0)

class RoastImage(models.Model):
    owner = models.ForeignKey(Roast, related_name='owner', on_delete=models.CASCADE)
    cloud_prefix = models.CharField(max_length=20)
    path = models.CharField(max_length=200)

class ContactInfo(models.Model):
    """
    We make this a database model since
    a company, shop, and roastery may have a
    common contact info. These values
    will all be unique.

    email
    phone number

    maybe more

    """
    pass

class Company(models.Model):
    """
    Parent object to a collection of shops
    and a collection of roasterys. As many
    coffee shops will serve other roasts, but 
    then expand into roasting as well.
    """
    owner = models.ForeignKey(USER_MODEL, related_name='company_owner', null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=240)
    roasterys = models.ForeignKey('Roastery', related_name='roasteries', null=True, on_delete=models.SET_NULL)
    shops = models.ForeignKey('Shop', related_name='shops', null=True, on_delete=models.SET_NULL)

class Shop(models.Model):
    """
    Represents a physical coffee shop.
    """
    owner = models.ForeignKey(USER_MODEL, related_name='shop_owner', null=True, on_delete=models.SET_NULL)
    serves_food = models.BooleanField()
    has_seating = models.BooleanField()
    roasts = models.ManyToManyField('Roast', related_name='shop_roasts')


    """
    location.. (maybe)
    """

class Roastery(models.Model):
    """
    Represents a physical roastery.
    """
    owner = models.ForeignKey(USER_MODEL, related_name='roastery_owner', null=True, on_delete=models.SET_NULL)
    roasts = models.ForeignKey('Roast', related_name='roastery_roasts', on_delete=models.CASCADE)

    """
    location.. (maybe)
    contact info (foreign key)
    user who owns the roastery
        *can be unclaimed (null)
    """

src/roast/forms.py
from django import forms

from roast.models import Roast

class RoastForm(forms.ModelForm):
    class Meta:
        model = Roast
        fields = ('name', 'color')

src/index/views.py
from django.shortcuts import render

src/roast/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from rest_framework import generics

from roast.models import Roast
from roast.serializers import RoastSerializer

class RoastPage(TemplateView):
    template_name = "roast_page.html"

    def get_context_data(self, pk, *args, **kwargs):
        context = super(RoastPage, self).get_context_data(*args, **kwargs)
        context["pk"] = pk
        return context

class RoastList(generics.ListCreateAPIView):
    queryset = Roast.objects.all()
    serializer_class = RoastSerializer

class RoastCrud(generics.RetrieveUpdateDestroyAPIView):
    queryset = Roast.objects.all()
    serializer_class = RoastSerializer

# class RoastList(ListView):
#     model = Roast
#     template_name = "roast_list.html"

src/index/templates/base.html
{% load static %}
<!doctype html>

<html lang="en" style="width: 100%; height: 100%; margin: 0; padding: 0">
<head>
  <meta charset="utf-8">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata|Merriweather" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script async defer src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2&appId=387893331992450&autoLogAppEvents=1"></script>
  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'base/base.css' %}">
</head>
<body style="width: 100%; height: 100%; margin: 0; padding: 0">
<div id="app">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarTogglerDemo01" 
        aria-controls="navbarTogglerDemo01" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
      </button>
      <h1><a class="navbar-brand" href="/">The Roast</a></h1>
      <div class="collapse navbar-collapse">
        <div class="mr-auto">
        </div>
        <ul class="navbar-nav">
          <li class="nav-item active">
            <div style="padding-right: 12px;">
              <div class="btn-toolbar" role="toolbar">
                <div class="btn-group" role="group">
                  {% if user.is_authenticated %}
                    <a href="{% url 'index:home' %}"><button style="margin-right: 6px" type="button" class="btn btn-outline-primary">Home</button></a>
                    <a href="{% url 'logout' %}"><button type="button" class="btn btn-outline-primary">Logout</button></a>
                  {% else %}
                    <button type="button" class="btn btn-lg btn-outline-light" data-toggle="modal" data-target="#loginModal">Login</button>
                    <button type="button" class="btn btn-lg btn-outline-light" data-toggle="modal" data-target="#loginModal">Signup</button>
                  {% endif %}
                </div>
              </div>
            </div>
          </li>
        </ul>
        <roast-search v-bind:options="{url: '/'}">
        </roast-search>
      </div>
    </div>
  </nav>
  <div style="margin: 0px; width: 100%; height: 100%;">
      <div class="row" style="height: 95%; width:100%; margin: 0px;">
          <div class="col">
          {% block leftcol %}
          {% endblock %}
          </div>
          <div class="col-8">
          {% block content %}
          {% endblock %}
          </div>
          <div class="col">
          {% block rightcol %}
          {% endblock %}
          </div>
      </div>
      <div class="row bg-dark" style="height: 5%; width: 100%;">
        {% comment %} <div class="col">
        </div>
        <div class="col-8">
        <a href="https://twitter.com/intent/tweet?button_hashtag=theroast&ref_src=twsrc%5Etfw" class="twitter-hashtag-button" data-show-count="false">Tweet #theroast</a>
        </div>
        <div class="col">
        </div> {% endcomment %}
      </div>
  </div>

  {% if not user.is_authenticated %}
  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
        </div>
        <div class="modal-body">
          <a href="{% url 'social:begin' 'google-oauth2' %}">Google</a>
          <br/>
          <a href="{% url 'social:begin' 'facebook' %}">Facebook</a>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Login</button>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="{% static 'base/base.js' %}"></script>
{% block post_body_static %}
{% endblock %}
</html>

src/index/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="home-app" style="margin-top: 12px">
    <h2 style="text-align: center; background-color: white;" id="roast-title"> ☕ Upload a new roast ☕ </h2>
    <hr style="margin-top: 24px"/>
    <form method="POST" action="{% url 'roast:create' %}">
        {% csrf_token %}
        <div class="form-group row">
            <div class="col">
                <form-label>Name:</form-label>
                <roast-input-line title="Name:" placeholder="Mighty Titan" name="name" style="margin-bottom: 6px;"></roast-input-line>
                <form-label>Short Description:</form-label>
                <roast-input-line title="Short Description:" placeholder="A powerful blend containing.." name="description" style="margin-bottom: 6px;"></roast-input-line>
                <form-label>Long Description:</form-label>
                <roast-input-line title="Long Description:" placeholder="A powerful blend containing.." name="description" style="margin-bottom: 6px;"></roast-input-line>
                <roast-image-upload title="Upload Images:"></roast-image-upload>
            </div>
        </div>
        <button type="submit" class="btn btn-dark btn-block shadow-lg mb-5 pill">Submit</button>
    </form>
</div>
{% endblock %}

{% block rightcol %}
{% endblock %}

{% block post_body_static %}
<script src="{% static 'home/home.js' %}"></script>
<style>
label {
    margin-top: 12px;
}

#roast-title {
    margin: 12px;

    /* #1 */
    border: 5px solid hsl(0, 0%, 40%);

    /* #2 */
    padding: 5px;

    /* #3 */
    outline: 5px solid hsl(0, 0%, 60%);

    /* #4 AND INFINITY!!! (CSS3 only) */
    box-shadow:
        0 0 0 10px hsl(0, 0%, 80%),
        0 0 0 15px hsl(0, 0%, 90%),
        0 0 0 20px hsl(0, 0%, 95%);
}
</style>
{% endblock %}

src/index/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div>
    <div id="main-jumbo" class="jumbotron jumbotron-fluid">
        {% comment %} Eventually this will become queries to the DB to get featured roasts {% endcomment %}
        <div class="container">
            <h1 class="display-6">Featured Roasts</h1>
            <div class="bd-example">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://placekitten.com/948/400" class="d-block w-100">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>First slide label</h5>
                                <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="https://placekitten.com/948/400" class="d-block w-100">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Second slide label</h5>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img src="https://placekitten.com/948/400" class="d-block w-100">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>Third slide label</h5>
                                <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% comment %} TODO: STYLE THIS HR {% endcomment %}
    <hr/>
    <div id='trending-box'>
        {% comment %} {% for item in trending.. %} {% endcomment %}
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="https://placekitten.com/100/180/" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
        {% comment %} {% endfor %} {% endcomment %}
    </div>
</div>

<script src="{% static 'index/index.js' %}"></script>
<link href="{% static 'index/index.css' %}" rel="stylesheet">

{% endblock %}

{% block rightcol %}
{% endblock %}

src/roast/templates/roast.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="roast-app">
    <roast_list>
    </roast_list>
</div>
{% endblock %}

{% block post_body_static %}
<script>

Vue.component('roast_list', {
    delimiters: ["[[", "]]"],
    data() {
        return {
            roasts: [],
        }
    },
    created() {
        var self = this;
        axios.get('/roast/create')
            .then(function (response) {
                response.data.forEach((r) => {
                    self.roasts.push(r)
                })
            })
            .catch(function (error) {
                alert(error);
            });
    },
    template: `
    <div>
        <ul style="padding: 0px;">
            <li 
                v-for="roast in roasts"
                style="list-style-type: none; padding-top: 12px;"
            >
                <roast_item
                    v-bind:title="roast.name"
                    v-bind:color="roast.color"
                    v-bind:description="roast.description"
                    v-bind:dark="true"
                ></roast_item>
            </li>
        </ul>
    </div>
    `,
})
Vue.component('roast_item', {
    props: ["title", "description", "color", "dark"],
    delimiters: ["[[", "]]"],
    template: `
    <div class="card" style="padding: 12px;" v-bind:class="{ 'text-white': dark, 'bg-dark': dark }">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">[[ title ]]</h5>
            <small>Color (1-100): [[ color ]]</small>
        </div>
        <p class="mb-1">[[ description ]]</p>
    </div>
    `,
})
</script>
{% endblock %}

src/roast/templates/roast_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<roast_page>
</roast_page>
{% endblock %}

{% block post_body_static %}
<script src="{% static 'components/roast_bar.js' %}"></script>

<script>
Vue.component('roast_page', {
    delimiters: ["[[", "]]"],
    created() {
        var self = this;
        axios.get('{% url 'roast:detail' pk=pk %}')
            .then(function (response) {
                self.roast = response.data
            })
            .catch(function (error) {
                alert(error);
            });
    },
    data() {
        return {
            roast: null
        }
    },
    template: `
    <div>
        <div>
            <div class="card bg-dark text-white" style="margin: 12px;">
                <div class="card-body" style="padding: 6px;">
                    <h1>[[ roast.name ]]</h1>
                </div>
            </div>
            <color-range
                v-bind:colors="[{ color: }]"
            />
        </div>
        <hr />
        <div>
            <div>
                <img src="https://placekitten.com/400/500" style="float: left;">
                <div style="float: left; margin-left: 12px;">
                    <h3>About this roast:</h3>
                    <hr />
                    <div>
                        [[ roast.description ]]
                    </div>
                </div>
            </div>
        </div>
    </div>
    `
})
</script>
{% endblock %}